application:
  port: 8000

database:
  host: 'localhost'
  port: 5432
  username: 'postgres'
  password: 'password'
  database_name: 'newsletter'

email_client:
  base_url: 'https://send.api.mailtrap.io/api/send'
  sender_email: 'mailtrap@demomailtrap.com'
  authorization_token: 'asdf'
  timeout_milliseconds: 1000
